version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: Abc@1234
      DB_NAME: fiber_demo
      DB_SSLMODE: disable
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc@1234
      POSTGRES_DB: fiber_demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
